name: Deploy tutorial

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: python -m pip install Sphinx

    - name: Build site
      working-directory: man
      run: make html

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./man/build/html
